version: '3.9'
services:
  backend:
    image: node:14.21.3
    container_name: adonis-backend
    working_dir: /backend
    volumes:
      - .:/backend
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=pg
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=admin
      - PG_PASSWORD=admin_password
      - PG_DB_NAME=my_database
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    command: ["sh", "-c", "npm install && node ace migration:run && node ace db:seed && node ace serve --watch"]
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
